FROM python:3.11-slim

WORKDIR /app

COPY app-backend/api/requirements.txt .
RUN pip install -r requirements.txt

COPY app-backend/api/ .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]