name: Deploy to Back-End

on:
  pull_request:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/myapp/CSC_4990_Capstone

            git fetch origin
            git sparse-checkout set app-backend
            git reset --hard origin/production

            cd app-backend/api

            source venv/bin/activate
            pip install -r requirements.txt

            sudo cp /home/ubuntu/myapp/CSC_4990_Capstone/app-backend/myapp-service/myapp.service /etc/systemd/system/myapp.service
            sudo systemctl daemon-reload
            sudo systemctl enable myapp
            sudo systemctl restart myapp